name: ondemand-build-nix-on-docker
on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: Environment name that stores configuration.nix
        required: true
        default: default
      
jobs:
  build-default-image:
    name: Build default image
    if: ${{ github.event.inputs.environmentName == 'default' }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Build SD Image
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.isoImage \
          -I nixos-config=./configuration.default.nix \
          --option sandbox false
    - uses: actions/upload-artifact@v3
      with:
        name: nixos.iso
        path: ./result/iso/*.iso*

  build-custom-image:
    name: Build custom image
    if: ${{ github.event.inputs.environmentName != 'default' }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Build SD Image
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.isoImage \
          -I nixos-config=./configuration.custom.nix \
          --option sandbox false
    - uses: actions/upload-artifact@v3
      with:
        name: nixos.iso
        path: ./result/iso/*.iso*
